name: fluocean
description: Oceanengine's Pangolin Plugin. Integrated pangolin advertising SDK, supports Android and IOS two platforms. Currently only integrated open screen ads and incentive ads
version: 0.1.2
homepage: https://github.com/qyxing/fluocean

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cn.originalstar.fluocean
        pluginClass: FluoceanPlugin
      ios:
        pluginClass: FluoceanPlugin

